stages:
  - publish

publish_to_pypi:
  stage: publish
  tags: 
    - shell # runner tags
    - linux
  script:
    # this will implicitly call poetry with the default settings on server  
    - poetry_default
  only:
    - tags  # Publish only on tagged commits


